name: Parse JETSCAPE_Authors.csv
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  csv-parser:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v3

      # run the python script to parse the csv file
      - name: Parse CSV
        run: |
          cd $GITHUB_WORKSPACE/scripts
          python3 parseCSV.py

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
